import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import Nav from '@/components/Nav'
=======
>>>>>>> c3dbe83 (start fresh)

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
<<<<<<< HEAD
  title: "Scrapbook",
  description: "Library of Photos",
=======
  title: "Create Next App",
  description: "Generated by create next app",
>>>>>>> c3dbe83 (start fresh)
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
<<<<<<< HEAD
      <body className="min-h-full flex flex-col">
        <Nav />
        {children}
        </body>
=======
      <body className="min-h-full flex flex-col">{children}</body>
>>>>>>> c3dbe83 (start fresh)
    </html>
  );
}
